site_name: "Wiki LeyChile (vigente)"
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - attr_list
  - tables
nav:
  - Inicio: index.md
  - Normas:
      - "Ley 21.719": normas/ley-21719.md
      - "Ley 21.459": normas/ley-21459.md
